version: "3.7"
services:
    bus_controller_app_srv:
        build:
            args:
                user: megatron
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: bus_controller_img
        container_name: bus_controller_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - bus_controller_net
    bus_controller_mysql_srv:
        image: mysql:5.7.14
        container_name: bus_controller_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker-compose/mysql/:/docker-entrypoint-initdb.d/
        networks:
            - bus_controller_net
    bus_controller_nginx_srv:
        image: nginx:alpine
        container_name: bus_controller_nginx
        restart: unless-stopped
        user: ":www-data"
        ports:
            - 8000:80
        volumes:
            - "./:/var/www:rw"
            - ./docker-compose/nginx/:/etc/nginx/conf.d/
        networks:
            - bus_controller_net
networks:
    bus_controller_net:
        driver: bridge
